# Generated by Django 5.1.5 on 2025-01-23 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='max_score',
            field=models.IntegerField(null=True),
        ),
    ]
