# Generated by Django 5.1.5 on 2025-01-24 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('exams', '0002_alter_exam_max_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('data_type', models.CharField(choices=[('str', 'String'), ('int', 'Integer'), ('float', 'Float'), ('bool', 'Boolean'), ('date', 'Date'), ('datetime', 'Datetime')], default='str', max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='exam',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='result',
            name='properties',
        ),
        migrations.CreateModel(
            name='BooleanResultProperty',
            fields=[
                ('resultproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.resultproperty')),
                ('value', models.BooleanField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('exams.resultproperty',),
        ),
        migrations.CreateModel(
            name='DateResultProperty',
            fields=[
                ('resultproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.resultproperty')),
                ('value', models.DateField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('exams.resultproperty',),
        ),
        migrations.CreateModel(
            name='DateTimeResultProperty',
            fields=[
                ('resultproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.resultproperty')),
                ('value', models.DateTimeField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('exams.resultproperty',),
        ),
        migrations.CreateModel(
            name='FloatResultProperty',
            fields=[
                ('resultproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.resultproperty')),
                ('value', models.FloatField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('exams.resultproperty',),
        ),
        migrations.CreateModel(
            name='IntegerResultProperty',
            fields=[
                ('resultproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.resultproperty')),
                ('value', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('exams.resultproperty',),
        ),
        migrations.CreateModel(
            name='StringResultProperty',
            fields=[
                ('resultproperty_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='exams.resultproperty')),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('exams.resultproperty',),
        ),
        migrations.AddField(
            model_name='resultproperty',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='exams.result'),
        ),
        migrations.AddField(
            model_name='resultproperty',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='exams.examattribute'),
        ),
        migrations.AddField(
            model_name='examattribute',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='exams.exam'),
        ),
    ]
