# Generated by Django 5.1.5 on 2025-01-24 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_resultproperty_examattribute_remove_exam_properties_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examattribute',
            name='code',
            field=models.CharField(default='changeme', max_length=50),
            preserve_default=False,
        ),
    ]
